version: "3.8"

services:
  mongo:
    container_name: mongo-container
    image: mongo:7
    restart: always
    volumes:
      - ./db:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    build: .
    image: superpoll-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/superpoll-api/dist
      - ./package.json:/usr/src/superpoll-api/package.json
    ports:
      - "3000:3000"
      - "9222:9222"
    links:
      - mongo
